# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

create_intrahost_component <- function() {
    .Call(`_EmodlibMalaria_create_intrahost_component`)
}

configure_intrahost_component <- function() {
    invisible(.Call(`_EmodlibMalaria_configure_intrahost_component`))
}

