Falciparum_MSP_Variants: 32
Falciparum_Nonspecific_Types: 76
Falciparum_PfEMP1_Variants: 1070
Run_Number: 12345
infection_params:
  Antibody_IRBC_Kill_Rate: 1.596
  Antigen_Switch_Rate: 7.645570124964182e-10
  Base_Gametocyte_Fraction_Male: 0.2
  Base_Gametocyte_Production_Rate: 0.06150582
  Base_Incubation_Period: 7
  Gametocyte_Stage_Survival_Rate: 0.588569307
  MSP1_Merozoite_Kill_Fraction: 0.511735322
  Merozoites_Per_Hepatocyte: 15000
  Merozoites_Per_Schizont: 16
  Nonspecific_Antigenicity_Factor: 0.415111634
  Number_Of_Asexual_Cycles_Without_Gametocytes: 1
  RBC_Destruction_Multiplier: 3.29
susceptibility_params:
  Antibody_CSP_Decay_Days: 90
  Antibody_Capacity_Growth_Rate: 0.09
  Antibody_Memory_Level: 0.34
  Antibody_Stimulation_C50: 30
  Erythropoiesis_Anemia_Effect: 3.5
  Fever_IRBC_Kill_Rate: 1.4
  Maternal_Antibody_Decay_Rate: 0.01
  Max_MSP1_Antibody_Growthrate: 0.045
  Min_Adapted_Response: 0.05
  Nonspecific_Antibody_Growth_Rate_Factor: 0.5
  Pyrogenic_Threshold: 15000.0
