// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// create_intrahost_component
IntrahostComponent* create_intrahost_component();
RcppExport SEXP _EmodlibMalaria_create_intrahost_component() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(create_intrahost_component());
    return rcpp_result_gen;
END_RCPP
}
// configure_intrahost_component
void configure_intrahost_component();
RcppExport SEXP _EmodlibMalaria_configure_intrahost_component() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    configure_intrahost_component();
    return R_NilValue;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_MalariaIntrahostEx();

static const R_CallMethodDef CallEntries[] = {
    {"_EmodlibMalaria_create_intrahost_component", (DL_FUNC) &_EmodlibMalaria_create_intrahost_component, 0},
    {"_EmodlibMalaria_configure_intrahost_component", (DL_FUNC) &_EmodlibMalaria_configure_intrahost_component, 0},
    {"_rcpp_module_boot_MalariaIntrahostEx", (DL_FUNC) &_rcpp_module_boot_MalariaIntrahostEx, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_EmodlibMalaria(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
