name: Run notebooks

on:
  push:
    branches:
    - master

jobs:
  run_notebooks:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        python-version: ['3.7', '3.11']

    steps:

    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Install requirements
      run: pip install .[full]; pip install nbconvert

    - name: Convert notebooks to Python
      working-directory: ./docs/tutorials
      run: find . -type f -name "*.ipynb" -exec jupyter nbconvert --to python --TemplateExporter.exclude_markdown=true {} \;

    - name: Convert notebooks to Markdown
      working-directory: ./docs/tutorials
      run: find . -type f -name "*.ipynb" -exec jupyter nbconvert --to markdown --TemplateExporter.exclude_code_cell=true {} \;
